version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi_service
    ports:
      - "8000:8000"
    networks:
      - backend_network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - backend_network

networks:
  backend_network:
